#ifndef PROVISIONING_CONFIG_HPP
#define PROVISIONING_CONFIG_HPP

// ProvisioningConfig.hpp — pure config-file builders for zero-touch phone
// auto-provisioning (Issue #35), served by GET /config/<mac>.cfg.
//
// Targets Yealink's plain-text auto-provisioning format (key = value, not
// XML) — the vendor pocket-dial already accommodates elsewhere in the
// codebase (the register-beep INVITE's Call-Info/Alert-Info/P-Auto-Answer
// headers exist specifically to make a Yealink auto-answer; see
// RegisterBeeper.cpp). Only PCMU/PCMA are offered: enforceG711() (see
// SipMessage) is the only codec path the server actually supports, so
// listing anything else would just be a codec the phone tries and the
// server never accepts.
//
// Not hardware-verified — there is no physical Yealink phone in this
// session — the key names and syntax below follow Yealink's long-stable,
// widely-documented auto-provisioning key set, but treat this as
// best-effort until confirmed against a real handset.

#include <string>

namespace provisioning
{
	// One phone's Yealink auto-provisioning config. `authRequired` says whether
	// this device must present a SIP digest to register — Registrar::Mode::
	// Secure, or a Learn-mode device individually promoted via
	// Registrar::secure(). The password field is always left blank either
	// way: Registrar/SipSecretStore only ever store HA1 = MD5(ext:realm:
	// secret), a one-way hash, so the server never has the plaintext secret
	// to provision with even when one is required — only whoever originally
	// set it does. When `authRequired` is true the config carries a comment
	// flagging that the admin still has to enter the password on the handset
	// by hand; the generated config still provisions everything else
	// (server, port, line, codecs), which is the tedious part either way.
	inline std::string yealinkConfigFor(const std::string& extension,
		const std::string& serverIp, int serverPort, bool authRequired)
	{
		std::string out;
		out.reserve(512);
		out += "#!version:1.0.0.1\r\n";
		out += "# Auto-generated by pocket-dial for extension " + extension + ". Issue #35.\r\n";
		if (authRequired)
		{
			out += "# This extension requires a SIP password pocket-dial cannot provision\r\n";
			out += "# automatically (only a one-way hash of it is stored server-side) --\r\n";
			out += "# set account.1.password by hand on this handset before it can register.\r\n";
		}
		out += "account.1.enable = 1\r\n";
		out += "account.1.label = " + extension + "\r\n";
		out += "account.1.display_name = " + extension + "\r\n";
		out += "account.1.auth_name = " + extension + "\r\n";
		out += "account.1.user_name = " + extension + "\r\n";
		out += "account.1.password = \r\n";
		out += "account.1.sip_server.1.address = " + serverIp + "\r\n";
		out += "account.1.sip_server.1.port = " + std::to_string(serverPort) + "\r\n";
		out += "account.1.sip_server.1.transport_type = 0\r\n";  // UDP
		out += "account.1.nat.udp_update_enable = 0\r\n";
		// PCMU (payload 0) then PCMA (payload 8) — the two enforceG711() keeps.
		out += "account.1.codec.1.enable = 1\r\n";
		out += "account.1.codec.1.payload_type = PCMU\r\n";
		out += "account.1.codec.1.priority = 1\r\n";
		out += "account.1.codec.2.enable = 1\r\n";
		out += "account.1.codec.2.payload_type = PCMA\r\n";
		out += "account.1.codec.2.priority = 2\r\n";
		return out;
	}
}

#endif
